spring:
  datasource:
    url: jdbc:h2:mem:gladb
    driverClassName: org.h2.Driver
    username: sa
    password: password

  web:
    resources:
      add-mappings: false

  mvc:
    throw-exception-if-no-handler-found: true
  endpoints:
      exposure:
        include: "*"
  info:
    env:
      enabled: true

info:
  app:
    name: "Project GLA Group A"
    description: "The server of an application used to find the shortest path between 2 stations"
    version: "1.0.0"

server:
  port: 8080
  servlet:
    context-path: "/api/v1"
  error:
    whitelabel:
      enabled: false

upload:
  dir: "src/main/java/fr/u_paris/gla/project/server/files-saved"

