image: maven:3-ibm-semeru-17-focal

stages:
    - test
    - sonarqube-check
    - coverage
    - deploy

test:app:
    stage: test
    script:
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent test jacoco:report
    artifacts:
        paths:
            - target/site/jacoco/jacoco.xml

sonarqube-check:
    stage: sonarqube-check
    image: maven:3-eclipse-temurin-17
    variables:
        SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"  # Defines the location of the analysis task cache
        GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task
    cache:
        key: "${CI_JOB_NAME}"
        paths:
            - .sonar/cache
    script:
        - mvn verify sonar:sonar
    allow_failure: true
    only:
        - merge_requests
        - main
        - dev

coverage:app:
    stage: coverage
    image: registry.gitlab.com/haynes/jacoco2cobertura:1.0.9
    script:
        - python /opt/cover2cover.py target/site/jacoco/jacoco.xml $CI_PROJECT_DIR/src/main/java/ > target/site/cobertura.xml
    needs:
        - test:app
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: target/site/cobertura.xml

deploy:app:
    stage: deploy
    script:
        - mvn deploy -s settings.xml
    rules:
        - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
